### ISSUE TITLE
Mason playbook ends prematurely

### ISSUE THREAD

**Issue by acritelli** [RITCCDC/regionals2018#39]
The logic below causes the entire series of playbooks for Mason to end, preventing subsequent roles (i.e. keyboxManaged) from being applied. Might just want to register a redmail_installed variable and use that to control things within this individual role.

```
- name: Check if iRedMail is installed
  uri:
    url: https://mason/mail/index.php
    validate_certs: no
  delegate_to: localhost
  register: return
  ignore_errors: yes

- name: End play if is installed
  meta: end_play
when: return.status == 200
```
