### ISSUE TITLE
Team Number Normalization - Spade

### ISSUE THREAD

**Issue by acritelli** [RITCCDC/regionals2018#65]
```
roles/spade/files/add_auth_server.py
roles/spade/files/cache_refresh.py
roles/spade/files/check_auth.py
roles/spade/files/setup.properties
```

@joe-graham I'll take setup.properties and you can take those three scripts, since they're yours.

**Comment by acritelli** [comment]
Should also fix this to use FQDN:

```
- name: Wait for webserver to come up
  uri:
    url: "https://spade/identity"
    status_code: 200
    validate_certs: no
  register: response_code
  until: response_code.status == 200
  retries: 60
  delegate_to: localhost
```
